
const enum ACTIONS {
  CLICK_TO_ITEM = "CLICK_TO_ITEM",
  SUBMIT_INPUT = "SUBMIT_INPUT",
  TYPE_INPUT = "TYPE_INPUT",
  CLEAR_COMPLETED_ITEM = "CLEAR_COMPLETED_ITEM",
  FILTERED_RADIO = "FILTERED_RADIO"
}

export {ACTIONS};